name: Automatyzacja Node.js App z MongoDB !!

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build&Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
    
      - name: Build and test Docker image
        run: |
          docker build -t node-mongo-app .
          docker run -d --name mongo mongo:5.0
          docker run -d --name app --link mongo -p 3000:3000 node-mongo-app
          sleep 10 
          curl http://localhost:3000 || exit 1

      - name: Push Docker image to Dockerhub
        if: success()
        run: |
          docker tag node-mongo-app ${{secrets.DOCKER_USERNAME}}/node-mongo-app:latest
          docker push ${{secrets.DOCKER_USERNAME}}/node-mongo-app:latest

  deploy: 
    name: Deploy to VPS
    runs-on: ubuntu-latest
    needs: build

    # Deploy with Terraform
    # steps:
    #   - name: Checkout 
    #     uses: actions/checkout@v3
    #   - name: Install Terraform
    #     uses: hashicorp/setup-terraform@v2
    #     with:
    #       terraform_version: 1.5.6
        
    #   - name: Inicjalizacja
    #     run: terraform init

    #   - name: Plan
    #     run: terraform plan

    #   - name: Zatwierdzanie planu i konfiguracji
    #     run: terraform apply -auto-approve
    steps:
       - name: Checkout 
         uses: actions/checkout@v3

       - name: Deploy to VPS
         uses: appleboy/ssh-action@v0.1.9
         with: 
           host: ${{secrets.VPS_HOST}}
           username: ${{secrets.VPS_USER}}
           key: ${{secrets.VPS_SSH_KEY}}
           port: 22
           script: |
             cd ~/terraform
             terraform init
             terraform apply -auto-aprove


    # Deploy with Docker
    # steps:
    #   - name: Checkout 
    #     uses: actions/checkout@v3

    #   - name: Deploy to VPS
    #     uses: appleboy/ssh-action@v0.1.9
    #     with: 
    #       host: ${{secrets.VPS_HOST}}
    #       username: ${{secrets.VPS_USER}}
    #       key: ${{secrets.VPS_SSH_KEY}}
    #       port: 22
    #       script: |
    #         docker stop app || true
    #         docker rm app || true
    #         docker pull ${{ secrets.DOCKER_USERNAME }}/node-mongo-app:latest
             
    #         # Uruchomienie kontenera MongoDB (jeśli nie działa)
    #         docker inspect mongo >/dev/null 2>&1 || \
    #         docker run -d --name mongo \
    #           -p 27017:27017 \
    #           mongo:5.0

    #         # Uruchomienie nowego kontenera aplikacji
    #         docker run -d --name app \
    #           -p 3000:3000 \
    #           --link mongo \
    #           ${{ secrets.DOCKER_USERNAME }}/node-mongo-app:latest
